[[language]]
name = "sql"
auto-format = false

[language.formatter]
command = "sqlfluff"
args = ["format", "--templater", "jinja", "--config", "/Users/rosslovelace/.sqlfluff", "--exclude-rules", "CP03", "-"]
